#include "core/blockchain.hpp"
#include "core/block.hpp"
#include "crypto/ecdsa.hpp"
#include <algorithm>
#include <stdexcept>
#include <string>
#include <vector>

Blockchain::Blockchain(int diff) : difficulty(diff) {
  Block genesisBlock = createGenesisBlock();
  genesisBlock.mine(difficulty);
  chain.push_back(genesisBlock);
}

Block Blockchain::createGenesisBlock() {
  return Block(0, std::vector<Transaction>{}, "0");
}

const Block &Blockchain::getLatestBlock() const { return chain.back(); }

void Blockchain::addTransaction(const Transaction &tx) {
  if (!isValidTransaction(tx)) {
    return;
  }

  // Double-spending prevention within mempool
  for (const auto &pendingTx : mempool) {
    for (const auto &pendingIn : pendingTx.inputs) {
      for (const auto &newIn : tx.inputs) {
        if (pendingIn.prevTxId == newIn.prevTxId &&
            pendingIn.outputIndex == newIn.outputIndex) {
          return; // Already spent in mempool
        }
      }
    }
  }

  mempool.push_back(tx);
}

void Blockchain::applyTransaction(const Transaction &tx) {
  // Coinbase transactions only have outputs
  if (!tx.inputs.empty()) {
    for (const auto &input : tx.inputs) {
      std::string key = generateUtxoKey(input.prevTxId, input.outputIndex);
      if (utxoSet.find(key) == utxoSet.end()) {
        throw std::runtime_error("Invalid Transaction: UTXO not found");
      }
      utxoSet.erase(key);
    }
  }

  for (size_t i = 0; i < tx.outputs.size(); i++) {
    std::string key = generateUtxoKey(tx.id, i);
    utxoSet[key] = tx.outputs[i];
  }
}

Transaction Blockchain::createCoinbase(const std::string &minerAddress,
                                       double fees) {
  double blockReward = 50.0;
  Transaction tx({}, {{minerAddress, blockReward + fees}});
  return tx;
}

void Blockchain::minePendingTransactions(const std::string &minerAddress) {
  double totalFees = 0;
  for (const auto &tx : mempool) {
    totalFees += tx.getValueIn(utxoSet) - tx.getValueOut();
  }

  Transaction coinbase = createCoinbase(minerAddress, totalFees);
  mempool.insert(mempool.begin(), coinbase);

  const Block &prev = getLatestBlock();
  Block newBlock(chain.size(), mempool, prev.hash);

  newBlock.mine(difficulty);
  chain.push_back(newBlock);

  for (const auto &tx : mempool) {
    applyTransaction(tx);
  }

  mempool.clear();
}

double Blockchain::getBalance(const std::string &address) const {
  double balance = 0;

  for (const auto &[key, value] : getUtxoFromAddress(address, utxoSet)) {
    balance += value.amount;
  }
  return balance;
}

UTXOset Blockchain::getUtxoSet() { return utxoSet; }

bool Blockchain::isValidTransaction(const Transaction &tx) const {
  // Case 1: Coinbase Transaction (generated by the system)
  if (tx.inputs.empty()) {
    // Only 1 output allowed in coinbase for reward + fees
    if (tx.outputs.size() != 1)
      return false;
    return true;
  }

  // Case 2: Regular Transaction
  if (!verifySignature(tx.publicKey, tx.calculateHash(), tx.signature)) {
    return false;
  }

  double valueIn = 0;
  for (const auto &input : tx.inputs) {
    std::string key = generateUtxoKey(input.prevTxId, input.outputIndex);
    auto it = utxoSet.find(key);
    if (it == utxoSet.end()) {
      return false; // UTXO does not exist or already spent
    }
    valueIn += it->second.amount;
  }

  double valueOut = tx.getValueOut();
  if (valueIn < valueOut) {
    return false; // Inflation attempt: spending more than owned
  }

  return true;
}

size_t Blockchain::getHeight() const { return chain.size(); }

const Block& Blockchain::getBlock(size_t index) const {
    if (index >= chain.size()) {
        throw std::runtime_error("Block index out of bounds");
    }
    return chain[index];
}

void Blockchain::addBlock(const Block& block) {
    if (isValidBlock(block, getLatestBlock())) {
        chain.push_back(block);
        for (const auto& tx : block.transactions) {
            applyTransaction(tx);
            // Remove from mempool
            auto it = std::find_if(mempool.begin(), mempool.end(), [&](const Transaction& t) {
                return t.id == tx.id;
            });
            if (it != mempool.end()) {
                mempool.erase(it);
            }
        }
    } else {
        throw std::runtime_error("Invalid block offered to blockchain");
    }
}

bool Blockchain::isValidBlock(const Block &current,
                              const Block &previous) const {
  if (current.previousHash != previous.hash) {
    return false;
  }

  if (current.hash != current.calculateHash()) {
    return false;
  }

  std::string target(difficulty, '0');

  if (current.hash.substr(0, difficulty) != target) {
    return false;
  }

  return true;
}

bool Blockchain::isChainValid() const {
  for (size_t i = 1; i < chain.size(); i++) {
    if (!isValidBlock(chain[i], chain[i - 1])) {
      return false;
    }
  }

  return true;
}
